### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by rafaelreuber** [rochacbruno/python-pagseguro#30]
Ao tentar usar python-pagseguro com python 3.3.5 obtive o erro abaixo.
O erro se da pela remoção do método iteritems da classe dict.

C:\Users\Reuber\env_notorium\Scripts\python.exe C:/Users/Reuber/PycharmProjects/pagseguro-sample/pague.py
Traceback (most recent call last):
  File "C:/Users/Reuber/PycharmProjects/pagseguro-sample/pague.py", line 24, in <module>
    response = pg.checkout()
  File "C:\Users\Reuber\env_notorium\lib\site-packages\pagseguro\__init__.py", line 227, in checkout
    self.build_checkout_params(**kwargs)
  File "C:\Users\Reuber\env_notorium\lib\site-packages\pagseguro\__init__.py", line 188, in build_checkout_params
    self.clean_none_params()
  File "C:\Users\Reuber\env_notorium\lib\site-packages\pagseguro\__init__.py", line 192, in clean_none_params
    for k, v in copy.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by rochacbruno** [comment]
:+1: are you sending a PR?

**Comment by rafaelreuber** [comment]
I'll do it as soon as possible
